#MODEL:
model_name: exp48_decoder26
model_type: experimental2
num_classes: 6
ignore_value: 255
pretrained_backbone: False

#OPTIM:
epochs: 1000
max_epochs: 1000
resume: False
lr: 0.05
momentum: 0.9
weight_decay: 0.0001
class_weight: null
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 3000
warmup_factor: 0.1

#TRAIN:
mixed_precision: True
run: 2
RNG_seed: 0
loss_type: bootstrapped
eval_while_train: True
exclude_classes: []

#benchmark
warmup_iter: 10
num_iter: 100
benchmark_loader: True
benchmark_model: True

#dataset
dataset_name: potsdam
dataset_dir: /root/dataset/potsdam
batch_size: 8
train_min_size: 400
train_max_size: 1600
train_crop_size: [1024,1024]
val_input_size: 1024
val_label_size: 1024
aug_mode: baseline
num_workers: 6
train_split: train
val_split: val
max_eval: 2000
validate_train_loader: False
eval_print_every: 1000
train_print_every: 1000

#checkpoint
pretrained_path: ''
save_every_k_epochs: 25
save_last_k_epochs: 30
save_dir: checkpoints
log_dir: training_log
save_name: potsdam1024_exp48_decoder26_1000_epochs
